### ISSUE TITLE
Error mysql 5.6 and 5.7

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#287] opened 2017-07-06 16:21 UTC
[MySQL]: ExecuteNonQuery(DELETE FROM tokens WHERE ( ((UNIX_TIMESTAMP(`validity`) - UNIX_TIMESTAMP()) <= ?where_lteqAND_1_UNIX_TIMESTAMP_validity_minus_UNIX_TIMESTAMP_))), MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect datetime value: '1499341550'
	  at MySql.Data.MySqlClient.MySqlStream.ReadPacket () [0x00096] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.NativeDriver.GetResult (System.Int32& affectedRow, System.Int64& insertedId) [0x00026] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.Driver.GetResult (System.Int32 statementId, System.Int32& affectedRows, System.Int64& insertedId) [0x00000] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.Driver.NextResult (System.Int32 statementId, System.Boolean force) [0x00023] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlDataReader.NextResult () [0x00205] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00315] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader () [0x00000] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery () [0x00033] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery (MySql.Data.MySqlClient.MySqlConnection connection, System.String commandText, MySql.Data.MySqlClient.MySqlParameter[] commandParameters) [0x00041] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery (System.String connectionString, System.String commandText, MySql.Data.MySqlClient.MySqlParameter[] parms) [0x0000d] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at WhiteCore.DataManager.MySQL.MySQLDataLoader.ExecuteNonQuery (System.String connStr, System.String sql, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean spamConsole) [0x00052] in <cb1604079d5e43c8a464e8f758653eba>:0

![pantallazo-0215](https://user-images.githubusercontent.com/428820/27921369-326e9794-623d-11e7-8810-3bbd4c792bfa.png)

both version of mysql with GRANT and without it

**Comment by johnfelipe** [comment] 2017-07-10 17:48
hi bros, im install, build and run in root, may be with that will works but again show this error:

	Jul 10 12:44:16 - [MySQL]: ExecuteNonQuery(DELETE FROM tokens WHERE ( ((UNIX_TIMESTAMP(`validity`) - UNIX_TIMESTAMP()) <= ?where_lteqAND_1_UNIX_TIMESTAMP_validity_minus_UNIX_TIMESTAMP_))), MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect datetime value: '1499692287'
	  at MySql.Data.MySqlClient.MySqlStream.ReadPacket () [0x00096] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.NativeDriver.GetResult (System.Int32& affectedRow, System.Int64& insertedId) [0x00026] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.Driver.GetResult (System.Int32 statementId, System.Int32& affectedRows, System.Int64& insertedId) [0x00000] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.Driver.NextResult (System.Int32 statementId, System.Boolean force) [0x00023] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlDataReader.NextResult () [0x00205] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00315] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader () [0x00000] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery () [0x00033] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery (MySql.Data.MySqlClient.MySqlConnection connection, System.String commandText, MySql.Data.MySqlClient.MySqlParameter[] commandParameters) [0x00041] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery (System.String connectionString, System.String commandText, MySql.Data.MySqlClient.MySqlParameter[] parms) [0x0000d] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at WhiteCore.DataManager.MySQL.MySQLDataLoader.ExecuteNonQuery (System.String connStr, System.String sql, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean spamConsole) [0x00052] in <6bac5ded5a624e029797fab655423b79>:0
	Jul 10 12:44:16 - [LLogin service]: All clear. Sending response to client for login to region ebim1 at <140.7792, 123.075, 21.02152>.
	WhiteCore.Server #

This is only in 

> root@ebimlab:~/WhiteCore-Dev/WhiteCoreSim# ./grid_console.sh

and when login with owner

**Comment by emperorstarfinder** [comment] 2017-07-10 19:01
John,

If you are in fact able to log in and teleport and otherwise interact in-world then it is safe to ignore this error as things will work as normal.  Unfortunately I am not able to reproduce this so I am at a loss as to what would be the cause as your table according to the image in another issue appears correct.

In the future when opening an issue please answer all questions as this helps us to get closer to a solution in a shorter order and attempt to reproduce the issue ourselves.  It also allows us to provide even better support.

**Comment by johnfelipe** [comment] 2017-07-10 19:13
@emperorstarfinder what about if you log in into my server?

**Comment by johnfelipe** [comment] 2017-07-10 19:25
"In the future when opening an issue please answer all questions as this helps us to get closer to a solution in a shorter order and attempt to reproduce the issue ourselves. It also allows us to provide even better support.", about that i think i already do, because i put all my steps and my edition and show via screenshot behaviour

**Comment by emperorstarfinder** [comment] 2017-07-11 01:48
@johnfelipe Lets run through a process to see if its just something with the DB tables you currently have first.  If this doesn't work then the next step would be for me to log into the server and look at whats going on.

Steps:

1. In the Database for WhiteCore delete the tables in their entirety (do not delete the table itself).
2. Start with a fresh copy of WhiteCore from the master branch of this repository.  (you will need to build it).
3. Configure using the built in configurator for WhiteCore.Server.sh in the WhiteCoreSim/bin/ directory.  (for this test don't use the grid_console.sh etc. as we want to see what exactly your getting in the log).
4. It will create the tables in the WhiteCore Database and migrate the correct data in the tables.
Upon this restart the grid server and create a normal user and an estate.  (normal user should be a user who is not a system account or grid owner account.)
5. Repeat step 3 for WhiteCore.sh found in the WhiteCoreSim/bin directory.  (for this test don't use the region_console.sh scripts etc.). It will ask you to create a user and region.  Go ahead and do so as the next step will override the user created for standalone.
6. Upon this completing do the run configurator command and configure it to run in grid mode by answering the questions it asks. after which it will create the files.  You will then need to restart the WhiteCore.sh instance.
7. Now your region server is in grid mode so it will ask again for the region owner name.  We want to give the region to the normal user you created.  Upon providing the user name it will configure and add the region to the estate.
8. Try logging the user in.  At this point that error your seeing with the UNIX_TIMESTAMP should go away.  
9. Let us know how this works out.  If it is still happening then the next step is for one of us to log into the server and see if theres an issue that is just not yet known.

**Comment by johnfelipe** [comment] 2017-07-11 12:27
@emperorstarfinder bro i put all with mariadb and is working, pls do it with mysql 5.6 or 5.7, because i do all test, for example with configurator is not creating region correctly

**Comment by emperorstarfinder** [comment] 2017-07-11 12:55
MariaDB is essentially the same as MySQL.  You don't need to use MySQL server if your using MariaDB.

**Comment by johnfelipe** [comment] 2017-07-11 12:57
@emperorstarfinder i can install all this:

         1. Install MySQL-5.7
         2. Install MySQL-5.6
         3. Install MySQL-5.5
         4. Install MariaDB-10.2
         5. Install MariaDB-10.1
         6. Install MariaDB-10.0
         7. Install MariaDB-5.5
         8. Install Percona-5.7
         9. Install Percona-5.6
        10. Install Percona-5.5
        11. Install AliSQL-5.6
I select **4**, but pls review with 1 and/or 2, i wil do your 9 steps only for help, but is working with MariaDB-10.2, but not with original MySQL-5.7/5.6

**Comment by emperorstarfinder** [comment] 2017-07-11 13:04
Where your on Linux I would stick with MariaDB.  MariaDB will work just fine with WC and in fact grids running on linux now adays are switching to MariaDB.

**Comment by johnfelipe** [comment] 2017-07-11 13:09
@emperorstarfinder i do all test, if not working pls ensure put in documentation for community, doing a note issue about original mysql, let you know today about my progress with your 9 steps.

**Comment by johnfelipe** [comment] 2017-07-11 15:53
https://goo.gl/YK49m4, that is record of my screen, show your steps and error about ebim1 region is created but not working
Stay alert

**Comment by johnfelipe** [comment] 2017-07-11 15:58
![pantallazo-0225](https://user-images.githubusercontent.com/428820/28077526-a26eb112-6627-11e7-86b5-5d55cfa5a243.png)

and put this

> Estate name [Owner's Estate]: ebimestado

and with whitecore i change region and works

![pantallazo-0226](https://user-images.githubusercontent.com/428820/28077613-dd3f2baa-6627-11e7-9599-ba6f9551d491.png)

but not showing in viewer

Stay alert

**Comment by johnfelipe** [comment] 2017-07-11 16:10
I reboot all, and show again error **UNIX_TIMESTAMP**, with error with region, look:

![pantallazo-0228](https://user-images.githubusercontent.com/428820/28078159-90820a92-6629-11e7-9f27-6ac7f0b490fd.png)

**Comment by fly-man-** [comment] 2017-07-11 22:42
Something I noticed in 1 of your pictures is that you're trying to run the WebUI on the Grid Server AND the Region server. This is where the 8004 error is about.

Can you issue on the grid server: grid clear all regions

Then all the regions are being removed from the grid server so they can register again.

Restart the region server and check the Grid server for the message that the region has successfully registered with the grid.

If that message doesn't appear, the region server isn't connecting to the grid server which will indeed give the error in your last image that no region is available.

**Comment by johnfelipe** [comment] 2017-07-11 22:45
Pls give me commands and where put it
Stay alert.

**Comment by emperorstarfinder** [comment] 2017-07-11 22:52
@johnfelipe The first thing that stands out is according to the video you do not actually have the region server configured to run in grid mode.  You actually do need to do the run configurator command on the region server and answer the questions it asks to configure it for grid mode.  then restart the region server.  The Grid Server URL will be the url to the actual grid server example: 192.168.0.1:8002

That would be why the region is not getting seen by the grid server and thus not actually showing up in the WebUI or prevents you from finding the region when logging in via viewer.

In regards the UNIX_TIMESTAMP error that should actually not prevent you from logging in.  Its an issue but not one that should affect your ability to interact in-world.  greythane and i are working on a fix to this as we do have some idea as to the cause.

**Comment by johnfelipe** [comment] 2017-07-13 14:09
then i need run configurator command in whitecore to?

**Comment by emperorstarfinder** [comment] 2017-07-13 21:57
That would be correct as i explained in the steps

**Comment by 65429812** [comment] 2017-12-19 08:35
请问，在AliSQL 5.6.32版本的AliSQL高性能K-V接口，InnoDB Memcached Plugin的扩展，这个功能有没有相关文档，如何验证？

**Comment by greythane** [comment] 2017-12-19 21:42
Closing this as the question appears to have been answered

**Closed by greythane** 2017-12-19 21:42 UTC
Labels: bug
