### ISSUE TITLE
Create a new group, wcs change not to the group name

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#172] opened 2015-12-08 18:14 UTC
When I make a new group, wcs change not to the group. I see in the list name "new group" not the group name, the I have created. And after relog to my region, the group is no more there. 

No errors in the console

System: Ubuntu 14.04 64bit grid mode

**Comment by BogusCurry** [comment] 2015-12-08 23:31
Hmm ... I will test it the fix ;D thanks for your support ;D

**Comment by influxWishdream** [comment] 2015-12-27 12:53
I can't seem to replicate the results. Though, it seems that the group creation didn't go through.
Do you have more information like if you're using MySQL?

**Comment by emperorstarfinder** [comment] 2016-01-15 02:01
Is the group actually being stored in the database? and which database are you using?

**Comment by emperorstarfinder** [comment] 2016-01-16 23:25
After further testing for Windows, Linux, etc. I have been unable to reproduce the issue @BogusCurry reports.  However, for those who have run into this issue the following should fix the issue:

1. after having configured your grid and region servers (via the console) do the following:
    a. Open Config/Sim/Data/Data.ini
    b. Change the following lines:

;; If you want to use SQLite, select this file.
;Include-SQLite = Sim/Data/SQLite.ini

;; If you want to use MySQL, select this file.
Include-MySQL = Sim/Data/MySQL.ini

   c. Edit Config/Sim/Data/MySQL.ini and put your database info to your grid database and save.
   d. re-run WhiteCore.exe

It appears even with the changes to make regions self dependent i.e. asset files stored in the filebased storage some things such as estate owner and groups etc still need to connect to the same database as the grid server.

The above step will not affect storage of assets but should ensure you can effectively create groups, estates, etc and connect regions properly.

Remember Groups is a grid service and therefore is not a region service technically.

**Comment by greythane** [comment] 2016-06-22 08:00
Using MySQL is the preferred option for multiuser systems but the default SQLite configuration will also work fine.

Closing this as the problem does not appear to be reproducible with the current code base ( and no further reports received in the meantime)

**Closed** 2016-06-22 08:00 UTC
Labels: bug
