### ISSUE TITLE
Question: How does one disable the File based asset service?

### ISSUE THREAD

**Issue by stormsonweathers** [WhiteCoreSim/WhiteCore-Dev#234] opened 2016-10-31 16:45 UTC
We're having lost asset issues using the current build with our server and traced it to the file asset service. Ive looked in the data.ini config but can't see where to reenable the old style .0.93 asset service or if its even possible.

Thanks in advance.

**Comment by greythane** [comment] 2016-10-31 22:55
Hmm... that's a bit of a worry :(

You can change back to the SQL based asset handler by setting "AssetHandler = AssetService"  rather than FileBasedAssetService.  This setting is found in the Data.ini of both the Grid and Sim configurations.

For a Grid setup change the setting in 
   Config/Grid/ServerConfiguration/Data/Data.ini 
For a grid attached region server, change the setting in
  Config/Sim/Grid/Grid.ini       (This is to tell the region server what to expect)
For a Standalone setup change the setting in
  Config/Sim/Data/Data.ini

Could you please let me know of the issues that you found and why you suspect that the File bases assets is the culprit ?

I had some suspicions about FileBased Assets running on a Windows system due to possible party length restrictions but as yet have not found any problems.

This is something that needs to be sorted out as the file based system appears to be inherently better  for reasons of duplication and backup of assets.
Greythane

**Comment by stormsonweathers** [comment] 2016-10-31 23:24
Here are some sample screencaps of the log screen (Sorry, was accessing remotely).

![media-20161031 2](https://cloud.githubusercontent.com/assets/7484424/19874946/253d7ff6-9f86-11e6-952b-0e0f9138acdc.png)
![media-20161031 2](https://cloud.githubusercontent.com/assets/7484424/19874952/29c8ed44-9f86-11e6-998f-a7211fa0524c.png)
![media-20161031](https://cloud.githubusercontent.com/assets/7484424/19874958/2f892096-9f86-11e6-9577-ef0c807a96a0.png)

As far as suspecting the asset service, I was trying to figure out why I was loosing assets until I noted the "File Based Asset Service" in the logs

**Comment by emperorstarfinder** [comment] 2016-10-31 23:42
I have tested this both on Windows and Nix.  

@stormsonweathers appears to be correct that assets are being lost in FileBasedAssets.  

The most noticeable thing visually when logged in that I can see is by loading an IAR (this was a very minimal test with loading an iar) there are empty folders both with create and merge being used.  In the console (console setting of set log level all) there doesn't appear to be a message that gives a noticeable clue that I can tell.  

The other visual thing in my tests I noticed is there appears to be difficulty with finding assets i.e. wearing clothing, skin, shapes, etc (at a minimum) which shows messages that the asset cannot be found to items taking a bit of time to actually rez in-world when rezzed from inventory.

While I haven't seen the messages displayed in the screenshots provided the one thing interesting that is showing is that MySQL thinks there is either a inventory_items_temp row in the inventory_items table or there is or is receiving a request or director for an inventory_items_temp row or table as there is a request to INSERT INTO 'inventory_items_temp * SELECT FROM 'inventory_items'.  After reviewing the WC database my tests created (with a clean database) there is no row or table for inventory_items_temp

I am inclined to recommend changing the label from question to bug as there appears to be an issue which needs to be resolved.

**Comment by greythane** [comment] 2016-11-01 00:33
Ok, a couple of things on first glance...

The errors shown appear to be a timeout issue with contacting the MySql server. .... 'connection failed to respond...' etc.
The warnings (in yellow) indicate that this is a first time run after an upgrade of the database tables schema, and whilst they can be safely ignored as they are 'normal', I'm wondering if the problem might be due to this schema update. Most of these are a change of format so that UUID's that are saved are of a consistent format.

It is possible that if the existing inventory is large (table data size) then the update of schema has the mysql server blocking and hence not responding timely to the data updates that will subsequently follow the migration.  
The process is...
  existing table > copy to temp table > update schema in existing table > reload all data from temp table back to the (old) existing table > remove temp table

Aside for the MySql errors, I cannot see any reference to the file based asset service in the screenshots?   
I can provide you with some sql scripts that will do the update manually if you wish to  try this.  Basically changing the schema as per the migration process but without all the data copying.

If the version change was from before we set file based assets as the main storage (April 2016) then any mysql assets would have been migrating to the file based system as they were being requested. This just involves retrieving the asset data from the MySQL instance and then re-writing to the file system. Subsequent access of that particular asset would then have been from the file based system, not MySQL.

Also note:  Inventory items contain details of assets but they do not contain the actual asset.  Even with the file based asset system in place, Inventory items are stored in the SQL database currently in use.

EmperorStarFinder :  Loading an IAR will result in empty folders if the IAR contains them.  This may not be due to 'losing an asset'.  Some more specific details on how to reproduce and check this would be appreciated. Sample IAR in question maybe  :)

G

**Comment by emperorstarfinder** [comment] 2016-11-01 00:40
Actually the empty folders had items in the folders.  Upon first upload of any iar (this does not appear to be specific to any single iar in any testing I have done thus far) I used the merge option which should in theory merge any folder in the iar with the items in that folder to the inventory in the standard way so its not in an iar or iar_import folder.  create seems to be doing the same thing.  there are no empty folders in any of the iars which I have tested that I am aware of.

**Comment by stormsonweathers** [comment] 2016-11-01 08:06
@greythane @emperorstarfinder :   I've changed the connect_timeout in MariaDB from 10 to 1000 (I'll fine tune tge varable later) and will try and remigrate the db and give you a heads up. BTW where would the new file based asset db is located?

**Comment by emperorstarfinder** [comment] 2016-11-01 13:33
I would also recommend increasing your max_allowed_packet to 100G (some DB cofigurations for MySQL / MariaDB will allow 1T).

For FileBasedAssets the files will be in the Data directory

**Comment by stormsonweathers** [comment] 2016-11-02 01:22
@emperorstarfinder  Thanks. After increasing the timeout to 1000, the errors still persisted. I didn't even think about increasing max_packets again since it's already set for 100M due to the amount of assets the grid has (so far, the DB is about 20GB while the .SIM file is at 1GB.)

**Comment by greythane** [comment] 2016-11-02 01:29
I suggest that a manual migration would be a better solution for that amount of data.
The copy and restructuring will block the server for a long time and as the migration code does not check (yet) it will assume pretty much instantaneous  updates :(

The errors you are getting are still for inventory... correct?
Are any other tables of considerable size (ignoring assets for now)?
Is it feasible to copy/dump/reload your entire database so that the updates can be done without effecting your current production one?  (Update copy and then reload/re-create production DB)

**Comment by stormsonweathers** [comment] 2016-11-02 01:37
@greythane The bulk of the db is assets, yes (assets by themselves is about 18gb alone). The rest of the tables are reasonable in comparison. I've been copying and reloading the db and I'm on my 4th db restore now) Yes, I've backed the production grid separately so it can be restored if I can't get the assets to work with the current build of WC.

**Comment by greythane** [comment] 2016-11-02 01:40
I'm not really sure that the file base asset stuff is the problem here. 
Can you email the log of the instance where you initially try to migrate to the new databases please? (greythane@gmai...)  I am interested in the errors and warnings that you are getting.

**Comment by emperorstarfinder** [comment] 2016-11-02 02:32
The reason I suggested increasing the max_allowed_packet to 100G is basically because sometimes a particular packet being imported to or exported from the DB can be bigger then the 16M or even 100M size of the allowed packet which ultimately would also cause the DB server to timeout.  In addition this potentially could help with migration updates as well especially where tables can get over 1G in size pretty fast.  While it probably shouldn't really be the first recommendation (and I don't normally do that unless I see a need to on my production grids) it is a good way to determine if the DB server is hanging up with the packet being to big for the max_allowed_packet size.

While I am inclined to agree that the direct cause may not be the FileBasedAssets itself, I would venture the guess that we are probably dealing with something not getting inserted correctly in the DB or something not getting inserted at all.  If this is the case this could explain potentially why assets are being lost.

**Comment by stormsonweathers** [comment] 2016-11-02 03:35
@greythane I've sent the logs to your email address.
@emperorstarfinder Yes, I've  noticed when the packet size is increased it helped speed things up and less crashes, but 100M seemed like a good size at the time. I'm waiting for my DB to complete restoring and will try the 100G settings to see if it works. Again,  will keep you both posted.

Again, thx both of you!

**Comment by stormsonweathers** [comment] 2016-11-04 02:37
@greythane @emperorstarfinder Just letting you guys know that the SQL script that Greythane emailed me worked like a charm! Even using the file based assets now. It also seemed to have fixed a couple of other issues I was having, but I think it may have been a coincidence since it wasn't asset related. Again thanks for the help!

**Closed** 2016-11-04 10:03 UTC
Labels: question
