### ISSUE TITLE
Particles not working correctly

### ISSUE THREAD

**Issue by TommyFDNY** [WhiteCoreSim/WhiteCore-Dev#122] opened 2015-01-09 01:35 UTC
Lots of troubleshooting on Google +; particles not working correctly.

![snapshot_001](https://cloud.githubusercontent.com/assets/10457533/5674259/740f9bca-9775-11e4-9d26-349608bc4e2f.jpg)

First screen shot is the script in WhiteCore

![snapshot_001](https://cloud.githubusercontent.com/assets/10457533/5674268/8a078032-9775-11e4-9766-710021356587.png)

Second is the test in SL.

This is the script:

default {
    state_entry() {
        llParticleSystem
        ([
            PSYS_PART_FLAGS,
            PSYS_PART_INTERP_COLOR_MASK|
            PSYS_PART_FOLLOW_SRC_MASK|
            PSYS_PART_EMISSIVE_MASK, PSYS_SRC_PATTERN,
            PSYS_SRC_PATTERN_ANGLE_CONE,
            PSYS_SRC_INNERANGLE, 0.0,     -------- These two lines are not enabled in WhiteCore, but 
            PSYS_SRC_OUTERANGLE, 0.1,    -------- are in SL/ LSL
            PSYS_SRC_BURST_SPEED_MIN, 0.0,
            PSYS_SRC_BURST_SPEED_MAX, 0.0,
            PSYS_SRC_BURST_RADIUS, 0.0,
            PSYS_SRC_BURST_PART_COUNT, 5,
            PSYS_SRC_BURST_RATE, 1.0,
            PSYS_PART_MAX_AGE, 1.0,
            PSYS_PART_START_SCALE, <1,1,1>,
            PSYS_PART_START_COLOR, <1,0.2,0.2>,
            PSYS_PART_END_COLOR, <1,0,0>,
            PSYS_PART_START_ALPHA, 1.0,
            PSYS_PART_END_ALPHA, 0.0
        ]);
    }
}

**Comment by nhede** [comment] 2015-01-09 18:10
I think whitecore sends the wrong default particle mask texture to the viewer. I think the default should be "c59f7fe-9dc8-47f9-8aaf-a9dd1fbc3bef" (not 100% shure yet) , this one is allready in the library inventory.
Also setting another texture inside the script, does not work.

**Comment by nhede** [comment] 2015-01-12 11:21
I think the problem is in libomv , fly-man- can you put the whitecore libomv on github?

**Comment by fly-man-** [comment] 2015-01-13 22:04
The most recent version of the LibOMV we use for Whitecore is in the repository now

**Comment by nhede** [comment] 2015-01-13 22:05
fixed (for the most part), see pull request

**Comment by nhede** [comment] 2015-01-13 22:08
fly-man- what repository, I don't see it https://github.com/WhiteCoreSim repositories

**Comment by fly-man-** [comment] 2015-01-13 22:08
https://github.com/WhiteCoreSim/WhiteCore-Dev 

We don't have a general LibOMV, each time when there's changes there's a binary rename that takes places on ours

**Comment by nhede** [comment] 2015-01-13 22:11
I need the the sources of libomv you are using too. For example I don't want all that j2k debug loggin (needs to be recompiled as release), Also want to do some j2k improvements to handle bad files.

**Comment by fly-man-** [comment] 2015-01-13 22:33
Setting this to my for the moment so I keep getting the updates. Nhede will take a deeper look into the LibOMV for this issue

**Comment by greythane** [comment] 2015-02-11 03:00
Checked this issue (with TommyFNDY) and particles do work correctly. This is may have been corrected with the referenced update or other.
Closing for now

**Closed by greythane** 2015-02-11 03:00 UTC
Labels: bug

**Comment by TommyFDNY** [comment] 2015-02-11 03:02
Yes, as I discussed. The particles are now working great :-)!
