### ISSUE TITLE
[bug] no textures from avatar loading after log in 

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#195] opened 2016-04-11 11:55 UTC
Hello ;D
I have local install the version 0.9.4.4 11-04-16 under Linux Mint 17.3 local as Grid. Now when I log in I see a cloud from my avatar. 
**And in the Console is this**
Apr 11 01:49:39 - [LLCLIENTVIEW]: Caught exception while processing OpenMetaverse.Packets.TransferRequestPacket for Bogus Curry, Object reference not set to an instance of an object   at WhiteCore.ClientStack.LLClientView.MakeAssetRequest (OpenMetaverse.Packets.TransferRequestPacket transferRequest, UUID taskID) <0x40bd3460 + 0x0014a> in <filename unknown>:0 
  at WhiteCore.ClientStack.LLClientView.HandleTransferRequest (IClientAPI sender, OpenMetaverse.Packets.Packet Pack) <0x40bd1eb0 + 0x0152b> in <filename unknown>:0 
  at WhiteCore.ClientStack.LLClientView.ProcessSpecificPacketAsync (System.Object state) <0x40b7db80 + 0x00090> in <filename unknown>:0 
 
Greetings

Bogus

**Comment by BogusCurry** [comment] 2016-04-13 12:54
This have found in the console too, when I log in .. 
Couldn't set missing image asset, falling back to missing image packet. This is known to crash the client

**Comment by BogusCurry** [comment] 2016-04-20 09:44
I have now test with the viewer Kokua, Replex, Firestorm and Alchemy in the last release, not the beta for linux. All viewer have the same issues message in the console and I can't see my ava ;(

**Comment by emperorstarfinder** [comment] 2016-04-20 12:23
Are you referring to the default avatar or an avatar you created or uploaded via IAR in the last few days?

**Comment by BogusCurry** [comment] 2016-04-20 13:37
nope, I have talk to greythane in irc. He means is clientside issues. I can't created a new shape, skin or so .. is very bad for me the situation.

**Comment by emperorstarfinder** [comment] 2016-04-20 13:51
Okay I will set up an environment today and try to see if i can reproduce this and see what is going on.  Usually if more then one viewer does the same thing on the same grid that would suggest server-side issues potentially relating to what is sent to the client for info and vice versa.

I assume you are using the latest mono as well?

**Comment by BogusCurry** [comment] 2016-04-20 15:22
I thinking the problem was for the changing from the filesystem from the Asset server not there. I can test under Windows too. Mono is the last rel. 4.2.3 and linux dist linux-mint 17.3 
Tomorrow, I have weekend, so I can more test the whitecore-sim

**Comment by emperorstarfinder** [comment] 2016-04-20 15:35
Okay I would recommend pulling a copy of the master before the changes were made for the Asset Service that @greythane  did and test to see if it does work.  If everything works for you there then at least we will then have something to work with here as arunning start.  

So lets have you test with the code from this commit: https://github.com/WhiteCoreSim/WhiteCore-Dev/commit/b70b0776bcd2224654380dfbd586ce68057b13be

If that works then we will have some idea as to the cause.

**Comment by greythane** [comment] 2016-04-21 04:54
I was able to check a similar setup out today and it does appear there are problems with Linux, but it does appear to be viewer based.

My check setup.
Running Linux Mint 17, (Ubuntu 14.04.1 - x64)
Server running the latest code (testing oar load #197 problem) - Grid mode
New install of latest Alchemy Beta
 - ran very slow ~ 2-3 fps  :(
- Avatar did not appear  (No shape, clothes etc) 
- Attached objects were visible.

Old Singularity V 1.8.5 (5617)
FPS was fine but still no Avatar shape, clothes etc. and again attached objects were visible.

Accessing the same server using a Mac viewer displayed everything normally.
Access from a windows viewer resulted in the 'cloud' with the appearance menu options disabled.
.... wondering if there are some firewall issues here...
I will investigate further .

**Comment by BogusCurry** [comment] 2016-04-21 05:06
yes I am now a test with the source b70b077 and my avatar is back ;D

I am in irc online ;D

**Comment by greythane** [comment] 2016-04-21 07:36
Thanks BogusCurry...  
I'll chase this up form that commit...

**Comment by emperorstarfinder** [comment] 2016-04-21 11:38
I had him check with that commit as I am not convinced yet that it is a client side issue.  Also Linux Mint is a bit phinicky as well and likely will be slower then other distributions based off of Ubuntu.  So far my testing on Linux (while chasing down a few pesky problems per discussions in IRC) indicate the best Linux distributions for Ubuntu based Linux to run WhiteCore on would be the main Ubuntu, KUbuntu, or XUbuntu.  I believe the problem here is in the changes to the Asset Service in Commit: https://github.com/emperorstarfinder/WhiteCore-Dev/commit/5d39e5ae697443ec4cd2ba0f89f8090e59158606 or Commit https://github.com/emperorstarfinder/WhiteCore-Dev/commit/e4b2023de246525980af000d554e748834b70b6d these commits are the ones that strike me as probably where this went off the track.

**Comment by BogusCurry** [comment] 2016-04-21 12:30
@emperorstarfinder I use many years Linux and have many run dists. Ubuntu is a good Dist, but is not my favorite. Linux-Mint with Xfce is very fast for me and so my favorite. That the viewer is slow, that is not only in whitecore sim. I have seen in opensim, is the same problem with the low fps. 
I run this version from wcs only as test, my grid was on a server under ubuntu 14.04. And the test was only local, not for public ;D

**Comment by emperorstarfinder** [comment] 2016-04-21 12:58
I like Linux Mint myself actually (because it does look similar to windows), the info I gave regarding the faster distributions is based on internal testing done with grid architecture and viewers.  Linux Mint is also a variant of Ubuntu (just written a little more user friendly and more bells and whistles) and does have Xfce UI.  I also have test environments set up for most major linux flavors out there i.e. OpenSuse, Fedora, CentOS, Ubuntu, Debian, etc.

So I give those recommendations based on testing obviously for grids being run in a production environment and open to the public.  But I do tend to run Linux Mint locally for my internal testing purposes because it sometimes does run slower as greythane has noticed.  

@greythane Linux Mint is also somewhat funny with the slow response calls in WebUtils for some folks.  On VU we increased the Timeout from your recommendation of 5000 to 10000 to help slower systems.  So far that seems to work for slower systems though I don't like doing that route myself.

**Comment by BogusCurry** [comment] 2016-04-21 13:15
I will test in the next days the both commits ;D

**Comment by BogusCurry** [comment] 2016-04-22 15:41
OK, I have now test both commits, by both can I see my avatar ;D

**Comment by BogusCurry** [comment] 2016-04-22 16:36
Sooo .. I now a little bit confused, I test now with the actual commit ! Under standalone modus and I see my avatar .. no issues at time ..

**Comment by emperorstarfinder** [comment] 2016-04-22 17:01
i am assuming you are still on Linux Mint 17.3?

**Comment by greythane** [comment] 2016-04-23 02:24
Bogus, just and update...
It appears the problem is associated with grid mode operation with seperate grid & region instances.
I have noted the same issue that is not apparent when running standalone.
I am debugging this now.

**Comment by BogusCurry** [comment] 2016-04-23 03:03
ok, thanks greythane ;D I will test it later ;D

**Comment by BogusCurry** [comment] 2016-04-25 13:46
@greythane I see you have make new patch ;D I have test and I see my avatar ... yeahh ;D

Thanks for you support ;D

**Comment by emperorstarfinder** [comment] 2016-04-25 13:53
Sounds like what I had thought was correct then with the grid service not being able to reach the asset service.  This is good.

**Comment by greythane** [comment] 2016-04-26 00:02
Closing as this has been corrected in the latest update (April 25th)
Commit # 4ed65733a4ca553d553cc0db71b038ffe086dcdf

**Closed by greythane** 2016-04-26 00:02 UTC
Labels: bug
