### ISSUE TITLE
Region not found

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#179] opened 2016-02-05 04:55 UTC
After long time 22/11/15, I have update over git my local gridserver. When I now log in, comes the message region not found ? Is that a bug or must I change everyfhing in the inis ?

**Comment by emperorstarfinder** [comment] 2016-02-05 05:05
This will generally mean either:

a) you have the url to your grid server not properly configured in your region server which can be fixed easily in the Config/Sim/Grid/GridCommon.ini.

b) you have your database server info incorrect (Note: you must use the same database service for your region server as your grid server.  i.e. MySQL or SQLite.  The FileBasedStorage handles the assets.)

c) you have a port that is being blocked by your firewall (either windows or router/ modem).

There isn't currently a known bug that would be causing this so the first guess is one of the 3 possibilities mentioned above.  If you can provide further info this will help to figure out what the issue is in the event there is a bug.  i.e. is the region showing up as registering with your grid server? etc.

**Comment by BogusCurry** [comment] 2016-02-05 05:10
no, the grid is only local, not online in internet. But I will see what say the ini file ;D

Thanks for your fast answer ;D

**Comment by emperorstarfinder** [comment] 2016-02-05 05:16
That should at least give you some idea those usually are the general issues but im not aware of an actual bug that would cause that.

**Comment by BogusCurry** [comment] 2016-02-05 05:39
Ok, I will make my local grid ;D 

thanks for help ;D

**Comment by greythane** [comment] 2016-02-05 09:09
Hi Bogus,
If your previous version was form November then changes in the ini files will be minimal.
The bigger problem is that if you are running from the WhiteCoreSim folder in your Git repo then any changes pulled from the master will overwrite your config and possibly others as well.

To run a local setup it is better to copy out the WhiteCoreSim folder entirely before you start configuring your grid.  e.g..  Use the repo to build the latest code but use a different location to run your actual grid.

To update this way just means you update your repo using git pull etc,  rebuild the latest code using the runprebuild or autobuild scripts and when finished, the update only involves copying the 'bin' folder from the repo WhiteCoreSim and replacing the same folder in your local running grid setup.

So essentially..
WhiteCore repo - Get updates and build the latest code
WhiteCoreSim - Copy of the repo folder, configured etc to your requirements
Update > Get the latest code (pull), build, copy the WhiteCoreSim\bin folder from the repo and replace the bin folder i your running grid.  
 ---  Restart, and continue.
 ---  This way most, if not all, details will be preserved and maybe only minor configuration changes are needed if something new has been introduced.

I'll try and get a tutorial on how to update on the whitecore-sim.org site  when I can.

**Comment by BogusCurry** [comment] 2016-02-05 09:21
Hi ;)
OK, thanks for you post greythan ;D The grid was a test for me, I will make new and then make a grid on my root server ;D
Greetings
Bogus

**Comment by emperorstarfinder** [comment] 2016-02-07 22:35
@BogusCurry when you go to try again be sure to pull the latest master as i think this might have been due to an accidental bug which is now fixed.

**Comment by BogusCurry** [comment] 2016-02-08 02:48
ahh ok, thanks ;D

**Comment by greythane** [comment] 2016-02-09 21:30
A bug crept in that tried to retrieve  the ownership of the region's parcels before they actually existed :(

Sorted in commit #9a0ca5b... of Feb 8th 2016

**Closed by greythane** 2016-02-09 21:30 UTC
Labels: bug
