### ISSUE TITLE
Loading OAR from console strips prims contents

### ISSUE THREAD

**Issue by Ramius1701** [WhiteCoreSim/WhiteCore-Dev#197] opened 2016-04-12 22:00 UTC
Version 0.9.4-Dev
Windows 10 (Yes i know windows ugh!)

Issue #1:
When loading a fresh oar from console it loads all the prims as expected, All the prims contents are stripped. Textures, scripts, animations, notecards, etc.

Created new sim, loaded different oar file, same issue.

Removed entire simulator and restarted from scratch, same issue

Issue #2:
Unable to transfer sim from real estate owner to newly created user and estate

Noticed this happening after doing a restart from scratch from issue #1

**Comment by greythane** [comment] 2016-04-12 22:05
Hi,
Loading OARS definitely works, at least with the old ones I have checked.
Is this a recent OAR or one of the freely available ones  (e.g. Linda Kelly etc)?
(Just wondering if something has changed in the formatting etc)
If it is possible and you can send me the OAR, I will check and see what is causing the load problem.

Re changing Estates...
There was a problem with that which was sorted out a while ago.  I'll re-check and see if it has crept back in again.

**Comment by emperorstarfinder** [comment] 2016-04-12 22:57
In Re the first issue were the permissions for the Textures, scripts, animations, notecards, etc. full permissions, Copy/Modify/Transfer etc in each of the OAR's used?  if not this might be due to permissions checking and the permissions may have blocked loading of those items.

@greythane if these are full permissions items etc. this might be due to the changes made with asset storage you recently did to.

**Comment by Ramius1701** [comment] 2016-04-13 01:25
The loading of OAR's was working until the last few builds of the Dev version.. These are my own designed OAR's with full perms and work fine in opensim

**Comment by greythane** [comment] 2016-04-13 02:59
Ok.. previously working throws a different light  :)
I have verified OAR loading using a new setup.. with not problems seen.

As of April 6th the asset system was changed from SQL based to File based.  This does involve some configuration changes that you might verify as if they are not done... assets will not be retrieved correctly.
Using a Diff type of program to compare folders is a good idea.


##For Grid mode  operation check these files...
WhiteCoreSim/Config/Grid/ServerConfiguration/Services.ini  (removed lines)
[Handlers]
>>>> Remove
  ;; Possible choices for asset services:
  ;;  AssetService - basic SQL service, slower, but works
  ;;  RedisAssetService - Redis database, fast, but memory hog
  ;;  FileBasedAssetService - Uses the file system to store assets, fastest   
  AssetHandler = AssetService
  AssetHandlerUseCache = false
<<<< Remove

;; Optional handlers

### Needs replacing as it has additional configuration options
WhiteCoreSim/Config/Grid/ServerConfiguration/Data/Data.ini

## For both Grid & Standalone
WhiteCoreSim/Config/Sim/Grid/Grid.ini
[Handlers]
AbuseReportHandler = AbuseReportsService
AgentInfoHandler = AgentInfoService
>>>> Remove
    AssetHandler = AssetService
    AssetHandlerUseCache = true
<<<< Remove
AuthenticationHandler = PasswordAuthenticationService

## For Standalone mode operation
WhiteCoreSim/Config/Sim/Standalone/Standalone.ini
AgentInfoHandler = AgentInfoService
>>>> Remove
  AssetHandler = AssetService
  AssetHandlerUseCache = true
<<<< Remove
AuthenticationHandler = PasswordAuthenticationService
AvatarHandler = AvatarService

### Needs replacing as it has additional configuration options
WhiteCoreSim/Config/Sim/Data/Data.ini

**Comment by Ramius1701** [comment] 2016-04-13 13:34
I checked on these and since this is a new simulator configuration (I deleted the old one and started new) these files are correct as described above. I deleted the old simulator with the thinking that a new setup would resolve the issues.

I have re-saved the OAR from opensim and tried loading again same issue. Took the same oar and loaded it into a different opensim (Diva Distro) and it worked there as it should. I removed the entire simulator and started from scratch and loaded the oar, still strips all the items from the prims. It does load the oar with all the base contents. All contents inside (ex. doors, elevators, texture changers, etc, etc) are removed during the loading of the oar. 

Changed to MySQL and loaded a completely different saved oar from opensim and it also loaded with all the correct prims, Still no prim contents.

**Comment by emperorstarfinder** [comment] 2016-04-13 13:36
Would it be possible to post a link to the OAR so it can be tested.  and does it give any errors in the consoles when your loading the OAR?

**Comment by Ramius1701** [comment] 2016-04-13 14:02
4 asset warnings about missing assets and one about mesh, the 4 warnings i believe are for textures and no mesh is on this particular oar. I dont have a way to post it currently, any suggestions :)

**Comment by emperorstarfinder** [comment] 2016-04-13 15:19
you can post the error messages you get here and you could post the oar using dropbox.com or a similar website

Also which physics engine are you using?

**Comment by greythane** [comment] 2016-04-13 21:26
Re the estate ownership problem.
Thanks for the bug report.

It appears that even though the estate is changed when doing so, the 'change estate' command always returns 'RealEstate Owner' as the current owner.
'show regions' does show the correct region estate.

I will re-visit this command and sort out the problem.

**Comment by greythane** [comment] 2016-04-13 23:02
Radius, just picking up on your comment...  '...the correct prims, Still no prim contents.'

Is the OAR loading correctly as far s terrain, objects (buildings etc)?
When you say 'contents' are you referring to ...say.. 
you have a shop which I think loads correctly?
... but anything within the shop is not loaded/displayed?  i.e.internal prims (chairs,tables, items etc)

**Comment by Ramius1701** [comment] 2016-04-14 00:41
Correct buildings, paths, doors, etc are loading, Any scripts or textures etc.etc that are stored within the prim are not being loaded. Prim memory seems to work since some texture animations are still working as of the last oar load. I reset all the perms in all prims containing scripts, textures, animations etc. inside the prim in opensim and reloaded the oar. These items are still not being loaded inside the prim itself.

I am running the basic configuration and did a fresh recomplie and only thing i changed was the myworld.ini file and set it to run locally on ip 127.0.0.1

**Comment by Ramius1701** [comment] 2016-04-14 01:26
Here is the link to the screen shots of the console showing the loading of the oar in WhiteCore and saving the oar in Opensim

http://imgur.com/a/yjJv8

**Comment by greythane** [comment] 2016-04-14 01:34
Thanks for the screen shots... 
It looks like the OAR and all the assets are loading correctly.  
Now I'll need to check if OS have done something new in saving the OAR that we are missing during the load ..  possibly linking of prime/assets to another container prim etc   :(

Any chance you can do something really simple on your OS setup?   
e.g..  small region, single object with prime inside etc.  
If I can get an OAR that exhibits the problem I can sort this one out otherwise I'll have to  fire up OS somewhere and try and re-create the problem... and that will take some time.

**Comment by Ramius1701** [comment] 2016-04-14 01:53
i will send the OAR via email, gmail account still good?

**Comment by Ramius1701** [comment] 2016-04-14 05:18
Tried an older version of the oar dated 2/9/16 as a test to see if the issue still presented itself and it was repeated with this OAR as well. I did an IAR import dated around the same time and that worked fine, an IAR import from today starts to load and then crashes WhiteCore.

I went back to version 0.9.3.14 and the oar loaded and all the prim contents are there. I also tested the IAR import from a backup on 2/9/16 and that imported fine in this version, the IAR from todays backup crashes the WhiteCore server

**Comment by fly-man-** [comment] 2016-04-14 06:36
I don't know the exact changes they made  but OAR and IAR's from Opensim won't work with WhiteCore as some of the changes that OS made aren't in WhiteCore.

**Comment by emperorstarfinder** [comment] 2016-04-14 13:06
I will be doing some testing on this one along with the other issues per our conversation in IRC the other day.  There may be some issues here with the way OS handles this now that we don't have yet as fly-man suggests.  I will know soon

**Comment by emperorstarfinder** [comment] 2016-04-14 22:45
A further look does in fact suggest we are missing a flag or two for 'export'  Opensim has also done a few other upgrades it appears to OARs and IARs which we also don't have so without those if the OAR or IAR comes from a recent version of Opensim it currently will not work and thus might reproduce this bug.

**Comment by greythane** [comment] 2016-04-15 01:15
Ok.  I think I have duplicated this problem... :)
Ramius, just to confirm that I am looking for the correct (missing) things..
.. The door scripts do not work in the latest build but they down the early build?
.. also if you can point me at something else that is missing it will help narrow down the problem.

**Comment by Ramius1701** [comment] 2016-04-15 01:34
On that particular sim (As it is a work in progress), all the doors, elevators, two screens and chairs in two of the buildings were scripted. My other sims are more complex but have the same issues, missing scripts for texture changers and textures in trees, NPCs, ambient sounds and scripts, Vendors, etc.etc.

**Comment by emperorstarfinder** [comment] 2016-04-18 12:31
Just a quick question so we can make sure we look for all possibilities in the OAR/ IAR piece to this.  That is the OAR and IAR you originally created when this started happening where they created initially on WhiteCore or Opensim?  This is a question I should have asked from the start.

**Comment by Ramius1701** [comment] 2016-04-19 03:12
There were originally created and currently updated on Opensim, Used with the defunct Aurora-Sim, and moved to White-Core. As changes progressed with each sim a copy was made for backup and use in Opensim and White-Core

**Comment by greythane** [comment] 2016-04-19 04:57
Radius,
You mentioned an IAR crashing the system.  Do you have the log for when this happened?
There are shared archiving processing being used for bot OAR's and IAR's and this may help me narrow the problem.   I suspect it is with a 'parent' or 'container' link not being processed correctly.

Working on this as it is something that I have introduced somewhere.. :(

**Comment by Ramius1701** [comment] 2016-04-19 06:21
During the import of an IAR backup, the console window starts to load scrolls some red text then closes without fully loading the IAR

**Comment by emperorstarfinder** [comment] 2016-04-19 14:09
can you post the messages from the log for it if its printing those messages to the log.  That will help narrow the IAR crashing.

**Comment by Ramius1701** [comment] 2016-04-19 21:18
Apr 13 09:23:58 -  [Inventory Archiver]: Loading archive ..\Data\UserArchives\Ramius.iar to inventory path IAR Import for Ramius Easterwood
Apr 13 09:23:59 -  [Archiver]: Commencing load from archive
Apr 13 09:23:59 -  [Inventory Archiver]: Loading version 0.3 IAR
Apr 13 09:23:59 -  [Inventory Archiver]: Restored 50 items...
Apr 13 09:23:59 -  [Inventory Archiver]: Restored 100 items...
Apr 13 09:23:59 -  [Inventory Archiver]: Restored 150 items...
Apr 13 09:24:00 -  [Inventory Archiver]: Restored 200 items...
Apr 13 09:24:00 -  [Inventory Archiver]: Restored 250 items...
Apr 13 09:24:00 -  [Inventory Archiver]: Restored 300 items...
Apr 13 09:24:00 -  [Inventory Archiver]: Restored 350 items...
Apr 13 09:24:00 -  [Inventory Archiver]: Restored 400 items...
Apr 13 09:24:00 -  [Inventory Archiver]: Restored 450 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 500 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 550 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 600 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 650 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 700 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 750 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 800 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 850 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 900 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 950 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 1000 items...
Apr 13 09:24:01 -  [Inventory Archiver]: Restored 1050 items...
Apr 13 09:24:02 -  [Inventory Archiver]: Restored 1100 items...
Apr 13 09:24:02 -  [Inventory Archiver]: Restored 1150 items...
Apr 13 09:24:02 -  [Inventory Archiver]: Restored 1200 items...
Apr 13 09:24:02 -  [Inventory Archiver]: Restored 1250 items...
Apr 13 09:24:02 -  [Inventory Archiver]: Restored 1300 items...
Apr 13 09:24:02 -  [Inventory Archiver]: Restored 1350 items...
Apr 13 09:24:02 -  [Inventory Archiver]: Restored 1400 items...
Apr 13 09:24:02 -  [Inventory Archiver]: Restored 1450 items...
Apr 13 09:24:03 -  [Inventory Archiver]: Restored 1500 items...
Apr 13 09:24:03 -  [Inventory Archiver]: Restored 1550 items...
Apr 13 09:24:04 -  [Inventory Archiver]: Restored 1600 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 1650 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 1700 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 1750 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 1800 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 1850 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 1900 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 1950 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2000 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2050 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2100 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2150 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2200 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2250 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2300 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2350 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2400 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2450 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2500 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2550 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2600 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2650 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2700 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2750 items...
Apr 13 09:24:05 -  [Inventory Archiver]: Restored 2800 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 2850 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 2900 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 2950 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 3000 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 3050 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 3100 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 3150 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 3200 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 3250 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 3300 items...
Apr 13 09:24:06 -  [Inventory Archiver]: Restored 3350 items...
Apr 13 09:24:07 -  [Inventory Archiver]: Restored 3400 items...
Apr 13 09:24:07 -  [Inventory Archiver]: Restored 3450 items...
Apr 13 09:24:08 -  [Inventory Archiver]: Restored 3500 items...
Apr 13 09:24:08 -  [Inventory Archiver]: Restored 3550 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 3600 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 3650 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 3700 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 3750 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 3800 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 3850 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 3900 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 3950 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 4000 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 4050 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 4100 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 4150 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 4200 items...
Apr 13 09:24:09 -  [Inventory Archiver]: Restored 4250 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4300 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4350 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4400 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4450 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4500 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4550 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4600 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4650 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4700 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4750 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4800 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4850 items...
Apr 13 09:24:10 -  [Inventory Archiver]: Restored 4900 items...
Apr 13 09:24:11 -  [Inventory Archiver]: Restored 4950 items...
Apr 13 09:24:12 -  [Inventory Archiver]: Restored 5000 items...
Apr 13 09:24:12 -  [Inventory Archiver]: Restored 5050 items...
Apr 13 09:24:13 -  [Inventory Archiver]: Restored 5100 items...
Apr 13 09:24:13 -  [Inventory Archiver]: Restored 5150 items...
Apr 13 09:24:14 -  [Inventory Archiver]: Restored 5200 items...
Apr 13 09:24:14 -  [Inventory Archiver]: Restored 5250 items...
Apr 13 09:24:15 -  [Inventory Archiver]: Restored 5300 items...
Apr 13 09:24:16 -  [Inventory Archiver]: Restored 5350 items...
Apr 13 09:24:17 -  [Inventory Archiver]: Restored 5400 items...
Apr 13 09:24:17 -  [Inventory Archiver]: Restored 5450 items...
Apr 13 09:24:18 -  [Inventory Archiver]: Restored 5500 items...
Apr 13 09:24:19 -  [Inventory Archiver]: Restored 5550 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 5600 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 5650 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 5700 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 5750 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 5800 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 5850 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 5900 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 5950 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6000 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6050 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6100 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6150 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6200 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6250 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6300 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6350 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6400 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6450 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6500 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6550 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6600 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6650 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6700 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6750 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6800 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6850 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6900 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 6950 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 7000 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 7050 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 7100 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 7150 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 7200 items...
Apr 13 09:24:20 -  [Inventory Archiver]: Restored 7250 items...
Apr 13 09:24:21 -  [Inventory Archiver]: Restored 7300 items...
Apr 13 09:24:21 -  [Inventory Archiver]: Restored 7350 items...
Apr 13 09:24:21 -  [APPLICATION]: 
APPLICATION EXCEPTION DETECTED

Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at WhiteCore.Modules.Archivers.InventoryArchiveReadRequest.Execute(Boolean loadAll) in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Modules\Archivers\Inventory\InventoryArchiveReadRequest.cs:line 188
   at WhiteCore.Modules.Archivers.InventoryArchiverModule.DearchiveInventory(String firstName, String lastName, String invPath, String loadPath, Dictionary`2 options) in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Modules\Archivers\Inventory\InventoryArchiverModule.cs:line 284
   at WhiteCore.Modules.Archivers.InventoryArchiverModule.HandleLoadIARConsoleCommand(IScene scene, String[] cmdparams) in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Modules\Archivers\Inventory\InventoryArchiverModule.cs:line 420
   at WhiteCore.Framework.ConsoleFramework.Commands.CommandSet.ExecuteCommand(String[] commandPath) in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:line 279
   at WhiteCore.Framework.ConsoleFramework.Commands.CommandSet.ExecuteCommand(String[] commandPath) in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:line 308
   at WhiteCore.Framework.ConsoleFramework.Commands.Resolve(String[] cmd) in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:line 93
   at WhiteCore.Framework.ConsoleFramework.LocalConsole.ReadLine(String p, Boolean isCommand, Boolean e) in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\LocalConsole.cs:line 670
   at WhiteCore.Framework.ConsoleFramework.CommandConsole.Prompt() in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:line 657
   at WhiteCore.Framework.ConsoleFramework.CommandConsole.ReadConsole() in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:line 906
   at WhiteCore.Simulation.Base.SimulationBase.Run() in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Simulation\Base\SimulationBase.cs:line 276
   at WhiteCore.Simulation.Base.BaseApplication.Startup(IConfigSource originalConfigSource, IConfigSource configSource, ISimulationBase simBase, String[] cmdParameters) in d:\My Downloads\WhiteCore-Dev-master\WhiteCore\Simulation\Base\BaseApplication.cs:line 614

Application is terminating: False

Apr 13 09:24:21 -  [Scene]: Closing down region: Sector 001
Apr 13 09:24:21 -  [FileBasedSimulationData]: Backing up Sector 001
Apr 13 09:24:21 -  [FileBasedSimulationData]: Saved Backup for region Sector 001
Apr 13 09:24:23 -  [RegisterRegionWithGrid]: Deregistering region Sector 001 at 1001, 1001 from the grid...
Apr 13 09:24:23 -  [Scene]: Closing down region: Universe Grid
Apr 13 09:24:23 -  [FileBasedSimulationData]: Backing up Universe Grid
Apr 13 09:24:23 -  [FileBasedSimulationData]: Saved Backup for region Universe Grid
Apr 13 09:24:25 -  [RegisterRegionWithGrid]: Deregistering region Universe Grid at 1000, 1000 from the grid...
Apr 13 09:24:25 -  [Shut Down]: Shut down processing on main thread complete.

**Comment by greythane** [comment] 2016-04-21 04:04
Finicky one that turned out to be a locking issue introduced during a previous inventory update.
This did not effect scripts (and possibly objects) already loaded and saved in the inventory previously.

Please check and advise.

**Comment by Ramius1701** [comment] 2016-04-21 07:16
The oar issue appears to be resolved now, All prims load, all script are there, all scripts start and function like they were designed too :)

**Comment by Ramius1701** [comment] 2016-04-21 07:19
Tested the transfer region ownership (Log details below)
Apr 21 01:17:25 -  [SceneManager]: Changed to region Universe Grid

-- transfer objects ownership:
      Transfers ownership of all objects on the region to another user.
-- transfer parcel ownership:
      Transfers ownership of all land in the region to another user.
-- transfer region ownership:
      Transfers all objects and land on the region to another user.

Apr 21 01:17:51 -  [APPLICATION]: 
APPLICATION EXCEPTION DETECTED

Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at WhiteCore.Modules.Permissions.PermissionsModule.HandleTransferOwnership(IScene scene, String[] args) in D:\My Downloads\WhiteCore-Dev-master\WhiteCore\Modules\World\Permissions\PermissionsModule.cs:line 524
   at WhiteCore.Framework.ConsoleFramework.Commands.CommandSet.ExecuteCommand(String[] commandPath) in D:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:line 279
   at WhiteCore.Framework.ConsoleFramework.Commands.CommandSet.ExecuteCommand(String[] commandPath) in D:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:line 308
   at WhiteCore.Framework.ConsoleFramework.Commands.Resolve(String[] cmd) in D:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:line 93
   at WhiteCore.Framework.ConsoleFramework.LocalConsole.ReadLine(String p, Boolean isCommand, Boolean e) in D:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\LocalConsole.cs:line 670
   at WhiteCore.Framework.ConsoleFramework.CommandConsole.Prompt() in D:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:line 657
   at WhiteCore.Framework.ConsoleFramework.CommandConsole.ReadConsole() in D:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\ConsoleFramework\CommandConsole.cs:line 906
   at WhiteCore.Simulation.Base.SimulationBase.Run() in D:\My Downloads\WhiteCore-Dev-master\WhiteCore\Simulation\Base\SimulationBase.cs:line 276
   at WhiteCore.Simulation.Base.BaseApplication.Startup(IConfigSource originalConfigSource, IConfigSource configSource, ISimulationBase simBase, String[] cmdParameters) in D:\My Downloads\WhiteCore-Dev-master\WhiteCore\Simulation\Base\BaseApplication.cs:line 614

Application is terminating: False

Apr 21 01:17:51 -  [Scene]: Closing down region: Universe Grid
Apr 21 01:17:52 -  [FileBasedSimulationData]: Backing up Universe Grid
Apr 21 01:17:52 -  [FileBasedSimulationData]: Saved Backup for region Universe Grid
Apr 21 01:17:54 -  [RegisterRegionWithGrid]: Deregistering region Universe Grid at 1000, 1000 from the grid...
Apr 21 01:17:54 -  [Scene]: Closing down region: Sector 001
Apr 21 01:17:54 -  [FileBasedSimulationData]: Backing up Sector 001
Apr 21 01:17:54 -  [FileBasedSimulationData]: Saved Backup for region Sector 001
Apr 21 01:17:55 -  [ATTACHMENTS MODULE]: Updating asset for attachment 481ec856-788c-4c6b-b47f-de2de23eaee3, attachpoint 38
Apr 21 01:17:56 -  [RegisterRegionWithGrid]: Deregistering region Sector 001 at 1001, 1001 from the grid...
Apr 21 01:17:57 -  [Shut Down]: Shut down processing on main thread complete. 


Apr 21 01:17:57 -  [HttpListenerManager]: Exception occurred: System.Net.HttpListenerException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
   at WhiteCore.Framework.Servers.HttpServer.HttpListenerManager.ListenerCallback(IAsyncResult result) in D:\My Downloads\WhiteCore-Dev-master\WhiteCore\Framework\Servers\HttpServer\HttpListenerManager.cs:line 117

**Comment by greythane** [comment] 2016-04-21 07:32
Hmmm..  Not a very tested command so anything is possible :)
Also, when you load an OAR, the ownership is transferred to the region owner, IF the original user does not exist.... 

The debug log is great and will help me sort the transfer problem. I am currently going through all the code and bring to sort all these 'null references' out... mostly inherited from OpenSim & Aurora

**Comment by Ramius1701** [comment] 2016-04-21 07:39
After loading the OAR everything appeared to be in my name, i didnt do a complete check of the one sim i loaded, Will go through and make sure :)

**Comment by emperorstarfinder** [comment] 2016-04-21 11:51
The other thing that catches my attention here is the fact that when these NullReference errors occur, we probably want it to stop crashing the console every time an error comes up.  (perhaps actually with all errors really).  

Also Ramius I noticed your using Universe Grid for one of your regions.  I would recommend changing that region's name as Universe Grid is a call used by Virtual Universe as a default grid name.  While it will not cause you problems code wise it might cause confusion among the developers as to which architecture your using when tracking down a bug.

**Comment by greythane** [comment] 2016-04-26 00:03
Closing as this has now been corrected. 
Commit # 80aa7c470e07d545d8ac3107dff2b14dafe857ed

**Closed by greythane** 2016-04-26 00:03 UTC
Labels: bug
