### ISSUE TITLE
EntityTransferModule.IncomingCreateObject - Physical objects

### ISSUE THREAD

**Issue by deasanta** [WhiteCoreSim/WhiteCore-Dev#135] opened 2015-06-04 12:33 UTC
Scenario
create one physical object and let it roll from 1000,1000 to 1000,1001

Setup
Standalone server with 4 regions of 256m
Version: WhiteCore 0.9.3 Dev Jun 05 2015 on win7x64
new server 2 static objects + 1 physical object + 1 avatar

Errors mention ODE

Errors shown below:

Jun 05 12:20:27 - [REGION]: Failed with exception System.NullReferenceException:
 Object reference not set to an instance of an object.
   at WhiteCore.Modules.EntityTransfer.EntityTransferModule.AddSceneObject(IScen
e scene, ISceneEntity sceneObject) in d:\WhiteCore\WhiteCore\Modules\World\Entit
yTransfer\EntityTransferModule.cs:line 776
   at WhiteCore.Modules.EntityTransfer.EntityTransferModule.IncomingCreateObject
(UUID regionID, ISceneEntity sog) in d:\WhiteCore\WhiteCore\Modules\World\Entity
Transfer\EntityTransferModule.cs:line 760
   at WhiteCore.Services.LocalSimulationServiceConnector.CreateObject(GridRegion
 destination, ISceneEntity sog) in d:\WhiteCore\WhiteCore\Services\GenericServic
es\SimulationService\LocalSimulationServiceConnector.cs:line 282
   at WhiteCore.Services.LocalSimulationServiceConnector.LocalSimulationServiceC
onnector_OnMessageReceived(OSDMap message) in d:\WhiteCore\WhiteCore\Services\Ge
nericServices\SimulationService\LocalSimulationServiceConnector.cs:line 121
   at WhiteCore.Services.SyncMessageRecievedService.<>c__DisplayClass4.<FireMess
ageReceived>b__0(MessageReceived messagedelegate) in d:\WhiteCore\WhiteCore\Serv
ices\GenericServices\MessagingService\SyncMessagingServices\SyncMessageRecievedS
ervice.cs:line 55
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at WhiteCore.Services.SyncMessageRecievedService.FireMessageReceived(OSDMap m
essage) in d:\WhiteCore\WhiteCore\Services\GenericServices\MessagingService\Sync
MessagingServices\SyncMessageRecievedService.cs:line 54
   at WhiteCore.Services.SyncMessagePosterService.Get(String url, OSDMap request
, GetResponse response) in d:\WhiteCore\WhiteCore\Services\GenericServices\Messa
gingService\SyncMessagingServices\LocalSyncMessagePosterService.cs:line 129
   at WhiteCore.Services.SimulationServiceConnector.CreateObject(GridRegion dest
ination, ISceneEntity sog) in d:\WhiteCore\WhiteCore\Services\GenericServices\Si
mulationService\SimulationServiceConnector.cs:line 301
   at WhiteCore.Modules.EntityTransfer.EntityTransferModule.CrossPrimGroupIntoNe
wRegion(GridRegion destination, ISceneEntity grp, Vector3 attemptedPos) in d:\Wh
iteCore\WhiteCore\Modules\World\EntityTransfer\EntityTransferModule.cs:line 707
   at WhiteCore.Modules.EntityTransfer.EntityTransferModule.CrossGroupToNewRegio
n(ISceneEntity grp, Vector3 attemptedPosition, GridRegion destination) in d:\Whi
teCore\WhiteCore\Modules\World\EntityTransfer\EntityTransferModule.cs:line 664
   at WhiteCore.Region.SceneObjectGroup.SetAbsolutePosition(Boolean UpdatePrimAc
tor, Vector3 val) in d:\WhiteCore\WhiteCore\Region\SceneObjectGroup.cs:line 3930

   at WhiteCore.Region.SceneObjectPart.PhysicsRequestingTerseUpdate() in d:\Whit
eCore\WhiteCore\Region\SceneObjectPart.cs:line 4613
   at WhiteCore.Framework.Physics.PhysicsActor.RequestPhysicsterseUpdate() in d:
\WhiteCore\WhiteCore\Framework\Physics\PhysicsActor.cs:line 165
   at WhiteCore.Physics.OpenDynamicsEngine.WhiteCoreODEPrim.UpdatePositionAndVel
ocity(Single timestep) in d:\WhiteCore\WhiteCore\Physics\OpenDynamicsEngine\WODE
Prim.cs:line 1681
   at WhiteCore.Physics.OpenDynamicsEngine.WhiteCoreODEPhysicsScene.Simulate(Sin
gle timeElapsed) in d:\WhiteCore\WhiteCore\Physics\OpenDynamicsEngine\WODEPhysic
sScene.cs:line 1500
   at WhiteCore.Region.SceneGraph.UpdatePhysics(Single elapsed) in d:\WhiteCore\
WhiteCore\Region\SceneGraph.cs:line 171
   at WhiteCore.Region.Scene.Heartbeat() in d:\WhiteCore\WhiteCore\Region\Scene.
cs:line 497 in region: Endertowe

Thanks for all for the hard work so far...

**Comment by greythane** [comment] 2015-06-18 04:20
Updates pushed to correct the main errors.
The problem is that the actual prim (object) data was not being retried correctly for the incoming scene.  Also, some additional permissions problems were found once that was corrected.

There still appears to be a problem with transferring the current physics state as a rolling sphere (for instance) will cross but immediately stop just inside the border of the new region.  This may or may not be a problem but I will continue to delve and see if the current physics state can be transferred as well.  i.e If the sphere was rolling, then continue rolling in the new region.

**Comment by deasanta** [comment] 2015-06-24 00:03
Thanks - suggestion to check - from an observation on opensim - you need enough velocity to complete the crossing. Without enough and it will get stuck on the border as it seems to be moving ever so slightly and jumping between the two regions thus causing many connections/handovers. IE object moving at 20 miles per hour have better chance of crossing cleanly than one moving at 0.02 miles per hour.

**Comment by greythane** [comment] 2015-06-29 21:23
Srry, been a bit busy here..
The crossings now occur without problem, the issue with not continuing after crossing may be 'normal' behaviour.  When rolling a sphere between two regions, I would expect that it would continue rolling once the border crossing is done... this does not seem to be the current behaviour and this is what I will continue to check through as time permits.

**Comment by fly-man-** [comment] 2015-10-01 23:11
Bumping this issue to 0.9.4 as it's a Physics issue

**Closed** 2016-08-29 22:56 UTC
Labels: bug
