### ISSUE TITLE
The problem with the entrance

### ISSUE THREAD

**Issue by LifeGold** [WhiteCoreSim/WhiteCore-Dev#215] opened 2016-08-20 12:08 UTC
### Steps to reproduce

1.The problem with the login server. When a lot of things users do, and others are unable at this time to log on to the server. Also when loading files the paddle until it is loaded on the server you can not enter.
https://youtu.be/67kBAlq4zBw

**Operating system**: Ubuntu

**WhiteCore version:** 0.9.4

**Comment by LifeGold** [comment] 2016-08-20 14:27
Also, if the server load has given today he is disabled in the logs nothing is clear in what the reason prompt. Here is the log file https://cloud.mail.ru/public/GReR/jgDmcEScg

**Comment by emperorstarfinder** [comment] 2016-08-20 16:14
The fact that you have things timing out indicates either 1) some ports are being blocked which is strange as Ubuntu by default does not have a firewall enabled, or 2) the host OS just needs to be rebooted which is a good idea to do at least once per week as sometimes the packet transfer rate will slow down.  Rebooting the server should correct this.

**Comment by LifeGold** [comment] 2016-08-20 18:10
Ports are open, server is restarted 2 times a day. Any other ideas?

**Comment by LifeGold** [comment] 2016-08-20 19:39
Kind of like helped increase this setting to 50 HttpThreadCount = 10

**Comment by LifeGold** [comment] 2016-08-20 21:58
Another mistake when several people simultaneously wear suits.

[CAPS]: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenMetaverse.Imaging.Baker.Bake () <0x4164bb30 + 0x02339> in <filename unknown>:0 
  at WhiteCore.Services.AgentAppearanceService.BakeAppearance (UUID agentID, Int32 cof_version) <0x415c1b70 + 0x011b3> in <filename unknown>:0 
  at WhiteCore.Services.AppearanceCAPS.UpdateAvatarAppearance (System.String path, System.IO.Stream request, WhiteCore.Framework.Servers.HttpServer.Implementation.OSHttpRequest httpRequest, WhiteCore.Framework.Servers.HttpServer.Implementation.OSHttpResponse httpResponse) <0x415c1560 + 0x000ee> in <filename unknown>:0

**Comment by greythane** [comment] 2016-08-21 02:13
LifeGold, a few questions to confirm what I am looking at please...

From the log you provided it appears that...
Your are running in Standalone mode?   ...or...  
...these are only the region server logs?

If grid mode, is the grid server running on the same system as the region server?
If no on the same server, I assume that both servers are on the same network?
... or is this set up a virtual server instance hosted in the cloud?  (AWS etc)

The code you are using does not appear to be the latest 'Dev' code as I can see details in the log that have been modified, if not corrected entirely. 

A large amount of the errors reported concern problems decoding textures. Earlier this month I pushed through a critical fix that caused multiple errors when trying to retrieve assets and this may be a problem here.

Greythane

**Comment by emperorstarfinder** [comment] 2016-08-21 02:23
LifeGold,

Please pull from master and build and retry.  Some of the issues your log indicates have actually been resolved so you may not likely have the fixes for these particular issues.

Some of these errors as Greythane has indicated are relating to textures failing to load causing problems with logins etc.  These were corrected so by pulling from the repository master and recompiling should correct most of these issues.

**Comment by LifeGold** [comment] 2016-08-21 08:18
When I last fly-man did the update downloaded, compiled and installed the latest version of the server. The server is on a VDS. The logs provided on the links above and grid and sim

**Comment by emperorstarfinder** [comment] 2016-08-30 22:54
After further testing and throwing every possible test I have at this issue to reproduce it which includes testing with the host operating system running at the extreme minimums of system resources, the end result is that i was unable to reproduce the reported problem.  Teleportation and attachments appear to be working properly and do not appear to be having issues.

The errors provided refer to missing textures or assets.  However this may even be a simple issue of updating the servers by pulling a copy of the latest repository master and compiling.  After compiling copy and pasting the bin folder in which case you would then have the most up-to-date versions of the OpenMetaverse dlls which could be an issue.

It is not recommended to compile the code directly in the same folder where your built copy of the servers is running in.  If the issue persists set the consoles to debug level by the command: set log level debug  

By using that log level this may help provide additional information if the problem persists.

Recommend closing as: Unable to reproduce.

**Comment by greythane** [comment] 2016-08-30 23:04
Closing due to lack of response for information and testing not being able to reproduce this issue.

**Closed by greythane** 2016-08-30 23:04 UTC
Labels: question
