### ISSUE TITLE
Able to walk/Fly off sim

### ISSUE THREAD

**Issue by Ramius1701** [WhiteCoreSim/WhiteCore-Dev#237] opened 2016-11-19 04:46 UTC
### Steps to reproduce

1. Walk or fly past sim borders in any direction

### Expected behaviour

Should hit the sim border and display message in chat "Cannot cross into non-existant region"

### Actual behaviour

Walk or fly in any direction past the sim border and you can go a great distance, map also show being off sim 

### Server configuration

Default configuration

**Operating system**:

Windows 8.1 and 10

**Web server:**

Built in

**Database:**

Built in

**WhiteCore version:**

Lastest dev version released on 11/16/16

### Logs

Console reports no errors

**Comment by greythane** [comment] 2016-11-19 06:52
This is not a bug but an expected behavior. The normal setting of regions on WhiteCore is to have "Infinite regions" where there are no apparent borders.

If the "Stop at the border" type of behavior is required it may be turned off or on, using the console command "set region infinite [yes/no]" once the desired region has been selected using the "change region ...." command.

**Comment by Ramius1701** [comment] 2016-11-19 09:37
That does explain a lot :)

If so anyway to prevent the sluggishness when going over the border?

**Comment by emperorstarfinder** [comment] 2016-11-19 15:44
The sluggishness is generally due to the state of the avatar or object's info being updated i.e. scripting engine and physics engine wise as that info has to be passed from one region to the next.  The delay should be minimal but depending on whether the two regions are being run in the same region console, on the same server, etc this could occur for a minute or two.  Just about every architecture out there (that includes Secondlife, Opensim, etc) have this issue with border crossings.  WC is very minimal compared to the rest here.

**Comment by greythane** [comment] 2017-07-21 05:14
Closing as this has been answered

**Closed by greythane** 2017-07-21 05:14 UTC
Labels: question
