### ISSUE TITLE
Multiple error with MySQL-5.7

### ISSUE THREAD

**Issue by johnfelipe** [WhiteCoreSim/WhiteCore-Dev#280] opened 2017-07-03 22:48 UTC
I have multiple errors with MySQL-5.7 in Sim and Grid, how resolve this, or may downgrade to MySQL-5.6

Stay alert

**Comment by greythane** [comment] 2017-07-03 23:28
Hi JohnFelipe,
Can you please get some log details showing these error that you are experiencing so I can check them out.
(I use WhiteCore with MariaDB 10)

**Comment by BogusCurry** [comment] 2017-07-04 11:08
Hi JohnFelipe ;D
What use you for a operating system ? I use Ubuntu 16.04 with sqlite, but this for a test. I would use, when I will make a grid, MariabDB or Mysql 5.6. The 5.7 release is very new and can make errors.
So I think is better downgrade or to use MariaDB ;D

Have a nice Day ;D
Bogus

**Comment by johnfelipe** [comment] 2017-07-04 11:19
I have Ubuntu 14, and MySQL 5.7, I will downgrade for test and let u know

**Comment by BogusCurry** [comment] 2017-07-04 17:39
When you have a long logfile, the best way put the errorlog in a past bin, here a link to a past bin ;D
https://paste.md-5.net/

So is better for the devs to look the errors ;D

Have a nice Day ;D

**Comment by emperorstarfinder** [comment] 2017-07-04 18:23
Hello John,

If you can provide the log details I can probably figure out what is going wrong.  It should be noted that when an error arises it is not necessarily because a version of MySQL is new and may just be something within WC itself.  

Also MariaDB is a great replacement for the mainstream MySQL server and is widely used.  In fact my grid runs on MariaDB.

**Comment by johnfelipe** [comment] 2017-07-04 20:58
I downgrade to Mysql 5.6 and this is error:

Second time: 
`screen -r Sim`
	 
	Estate owner name (/User Name) []: felipe urrego
	Do you want to 'park' the region with the system owner/estate? (yes/no) [yes]: enter

	Jul 04 03:56:17 - [EVENT MANAGER]: Delegate for StartupComplete failed - continuing.  System.NullReferenceException: Object reference not set to an instance of an object
	  at WhiteCore.Modules.Sun.SunModule.EventManager_OnStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] data) [0x00028] in <d01b8503b0fa49b6b0ff3792b62404e5>:0
	  at WhiteCore.Framework.SceneInfo.EventManager.TriggerStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] StartupData) [0x00029] in <aba23f3718e649889efa69591d853d01>:0    at WhiteCore.Modules.Sun.SunModule.EventManager_OnStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] data) [0x00028] in <d01b8503b0fa49b6b0ff3792b62404e5>:0
	  at WhiteCore.Framework.SceneInfo.EventManager.TriggerStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] StartupData) [0x00029] in <aba23f3718e649889efa69591d853d01>:0
	Jul 04 03:56:17 - [WebUtils] Request failed - (URI:SyncMessageServerURI, METHOD:POST) : The request URI must either be an absolute URI or BaseAddress must be set
	Jul 04 03:56:17 - [SceneManager]: Startup Complete. This took 0m 45.813s

**Comment by johnfelipe** [comment] 2017-07-04 21:02
when login with firestorm 5.0.1.52150, show this:

	Jul 04 04:00:38 - [Client]: Caught exception while processing OpenMetaverse.Packets.CompleteAgentMovementPacket for felipe urrego, Object reference not set to an instance of an object   at WhiteCore.Modules.Permissions.PermissionsModule.InternalIsAdministrator (OpenMetaverse.UUID user, System.Boolean checkGodStatus) [0x00042] in <d01b8503b0fa49b6b0ff3792b62404e5>:0
	  at WhiteCore.Modules.Permissions.PermissionsModule.IsAdministrator (OpenMetaverse.UUID user) [0x00000] in <d01b8503b0fa49b6b0ff3792b62404e5>:0
	  at WhiteCore.Framework.SceneInfo.ScenePermissions+<>c__DisplayClass221_0.<IsAdministrator>b__0 (WhiteCore.Framework.SceneInfo.IsAdministratorHandler h) [0x00000] in <aba23f3718e649889efa69591d853d01>:0
	  at System.Linq.Enumerable.All[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0002c] in <26aedeede9534b948c539f8734c8492d>:0
	  at WhiteCore.Framework.SceneInfo.ScenePermissions.IsAdministrator (OpenMetaverse.UUID user) [0x00022] in <aba23f3718e649889efa69591d853d01>:0
	  at WhiteCore.Modules.Land.LandObject.IsBannedFromLand (OpenMetaverse.UUID avatar) [0x0000b] in <d01b8503b0fa49b6b0ff3792b62404e5>:0
	  at WhiteCore.Modules.Estate.EstateSettingsModule.OnAllowedIncomingTeleport (OpenMetaverse.UUID userID, WhiteCore.Framework.SceneInfo.IScene scene, OpenMetaverse.Vector3 position, System.UInt32 teleportFlags, OpenMetaverse.Vector3& newPosition, System.String& reason) [0x00226] in <d01b8503b0fa49b6b0ff3792b62404e5>:0
	  at WhiteCore.Framework.SceneInfo.ScenePermissions.AllowedIncomingTeleport (OpenMetaverse.UUID userID, OpenMetaverse.Vector3 Position, System.UInt32 TeleportFlags, OpenMetaverse.Vector3& newPosition, System.String& reason) [0x00025] in <aba23f3718e649889efa69591d853d01>:0
	  at WhiteCore.Region.ScenePresence.CompleteMovement (WhiteCore.Framework.PresenceInfo.IClientAPI client) [0x00037] in <8b2a139a106b4e3381e1da3bdaaef330>:0
	  at WhiteCore.ClientStack.LLClientView.HandleCompleteAgentMovement (WhiteCore.Framework.PresenceInfo.IClientAPI sender, OpenMetaverse.Packets.Packet pack) [0x0000a] in <d5d8f7d439e94f319c6dacfd0a4429cc>:0
	  at WhiteCore.ClientStack.LLClientView.ProcessSpecificPacketAsync (System.Object state) [0x00007] in <d5d8f7d439e94f319c6dacfd0a4429cc>:0

**Comment by johnfelipe** [comment] 2017-07-05 15:18
What about this?

**Comment by greythane** [comment] 2017-07-05 21:35
Hi JohnFelipe,

I am suspicious that both of these errors are related to a problem with your user account.
As previous questions relate to problems with your database it is a bit difficult to  suggest how to continue.

To verify that your build is ok..
Re-build WhiteCore using one of the supplied scripts (Windows/*nix)
Copy the entire WhiteCoreSim folder to somewhere temporary (This will be deleted after verification)
Change to the copied WhiteCoreSim folder
Do not change any configuration files
If your system is a unix based system, start WhiteCore using the 'run_standalonemode.sh' script
If your system is Windows, start WhiteCore using the 'sim_standalone_console.bat' script

Please report any errors that you get here.
If WhiteCore runs correctly in standalone mode then your build is ok.  You can use the same WhiteCoreSim folder and modify as required.

**Comment by johnfelipe** [comment] 2017-07-05 21:38
But my error is in gridmode, i dont need standalone mode

**Comment by greythane** [comment] 2017-07-05 22:02
I am aware of this but I also have no idea of how your system is configured, what the database is like or basically everything about your setup. Also, you have asked questions about errors in startup, then about login, which implies that your system did startup. Later you reference errors in loading an oar which suggests that you actually have your system running.
At this point I really have no idea what state your installation is at.

Running in standalone mode from a clean build would just verify that your compilation is running correctly on your system without any additional external influences.. e.g. database etc.

**Comment by johnfelipe** [comment] 2017-07-05 22:55
Ok i will do it in my snapshot of ubuntu, i let u know in couple of hours

**Comment by johnfelipe** [comment] 2017-07-06 00:05
I do this steps:

	git clone --recursive https://github.com/WhiteCoreSim/WhiteCore-Dev.git
	cd WhiteCore-Dev/

	./runprebuild.sh

	x64 architecture found
	Architecture to use? (x86, x64) [x64]: x64
	Configuration? (Release, Debug) [Debug]: Release
	Build immediately? (Yes, No) [No]: Yes

show me this log:

https://paste.md-5.net/luweqeyeyi.sm

Next i do this

	felipe@ebimlab:~/WhiteCore-Dev/WhiteCoreSim$ ./run_standalonemode.sh
	Starting Standalone Region Simulator...
	There is a screen on:
			3315.Sim        (07/05/2017 06:46:23 PM)        (Detached)
	1 Socket in /var/run/screen/S-felipe.

	To view the Sim console, use the command : screen -r Sims
	To detach fron the console use the command : ctrl+a d  ...ctrl+a [command mode],  d [detach]

enter to screen and:

	Grid owner user name (? for suggestion) [Othal Marcie]: felipe urrego
	Password: felipe
	Re-enter Password: felipe
	Email for password recovery. ('none' if unknown) [none]: ingenierofelipeurrego@gmail.com
	Required avatar UUID (optional)) [3a3bf721-2bfb-4cbb-800c-a353b439eecf]: enter

	Region Name (? for suggestion) []: ebim1
	Region Location X [1000]: 1000
	Region location Y [1000]: 1000
	Region size X [256]: 256
	Region size Y [256]: 256
	Region Type (Mainland / Estate / Homes) [Estate]: enter
	Estate region type?, Options are [Full Region] [Full Region]: Full Region
	Terrain Type?, Options are [Flatland, Grassland, Hills, Mountainous, Island, Swamp, Aquatic] [Grassland]: Grassland
	Estate owner name (RealEstate Owner/User Name) [RealEstate Owner]: felipe urrego
	Do you want to 'park' the region with the system owner/estate? (yes/no) [yes]: enter


all normal

next, load oar and only error show me is this:

`Jul 05 06:59:38 - [J2K Image]: Texture block copy for the first packet failed. textureid=b33ce259-1ab8-407d-ada0-b6101c701674, assetlength=5496, currentposition=2147483600, imagepacketsize=1000, exception=Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.`

**Comment by johnfelipe** [comment] 2017-07-06 01:47
with mysql 5.7 i do this:

	nano /home/felipe/WhiteCore-Dev/WhiteCoreSim/Config/Sim/Main.ini

	##
	;;If you would like to use WhiteCore in standalone mode , select this file.
	Include-Standalone = Sim/Standalone/StandaloneCommon.ini

	To 

	;;If you would like to use WhiteCore in standalone mode , select this file.
	;Include-Standalone = Sim/Standalone/StandaloneCommon.ini

	and

	;;If you would like to use WhiteCore in grid mode, select this file.
	;Include-Grid = Sim/Grid/GridCommon.ini

	To

	;;If you would like to use WhiteCore in grid mode, select this file.
	Include-Grid = Sim/Grid/GridCommon.ini
	##


	Grid = Config/Grid/ServerConfiguration/Data/Data.ini
	
	comment the "Include-SQLite" line
	uncomment the "Include-MySQL" line

	Grid = Config/Grid/ServerConfiguration/Data/MySQL.ini

	##

	[WhiteCoreData]
	;;
	;; Change the connection string to your db details
	;; NOTE: This sets up the database for all grid services
	;; 
	ConnectionString = "Data Source=localhost;Port=3306;Database=xxxxx;User ID=xxxxx;Password=xxxxx;Charset=utf8;"

	StorageProvider = MySQL
	##


	cd WhiteCore-Dev/
	cd WhiteCoreSim/
	./grid_console.sh

	Grid owner user name (? for suggestion) [Spamfast Spamfast]: felipe urrego
	Password: xxx
	Re-enter Password: xxx
	Email for password recovery. ('none' if unknown) [none]: ingenierofelipeurrego@gmail.com
	Required avatar UUID (optional)) [c819b66b-6e1f-4235-8290-e04ebf60d3f4]: enter

in another window

	cd WhiteCore-Dev/WhiteCoreSim/bin/

	./WhiteCore.sh

	Region Name (? for suggestion) []: ebim1
	Region Location X [1000]: 1000
	Region location Y [1000]: 1000
	Region size X [256]: 256
	Region size Y [256]: 256
	Region Type (Mainland / Estate / Homes) [Estate]: Estate
	Estate region type?, Options are [Full Region] [Full Region]: Full Region
	Terrain Type?, Options are [Flatland, Grassland, Hills, Mountainous, Island, Swamp, Aquatic] [Grassland]: Flatland
	Estate owner name (RealEstate Owner/User Name) [RealEstate Owner]: felipe urrego
	Do you want to 'park' the region with the system owner/estate? (yes/no) [yes]: enter


quit all services and restart

	screen -r Grid 

	Estate name [Owner's Estate]: Myestate

login and show me this

	Jul 05 08:39:28 - [LLogin service]: Login request for felipe urrego from 190.251.131.150 with user agent Firestorm-Release 4.7.7.48706 starting in last
	Jul 05 08:39:28 - [MySQL]: ExecuteNonQuery(DELETE FROM tokens WHERE ( ((UNIX_TIMESTAMP(`validity`) - UNIX_TIMESTAMP()) <= ?where_lteqAND_1_UNIX_TIMESTAMP_validity_minus_UNIX_TIMESTAMP_))), MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect datetime value: '1499288606'
	  at MySql.Data.MySqlClient.MySqlStream.ReadPacket () [0x00096] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.NativeDriver.GetResult (System.Int32& affectedRow, System.Int64& insertedId) [0x00026] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.Driver.GetResult (System.Int32 statementId, System.Int32& affectedRows, System.Int64& insertedId) [0x00000] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.Driver.NextResult (System.Int32 statementId, System.Boolean force) [0x00023] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlDataReader.NextResult () [0x00205] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x00315] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader () [0x00000] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery () [0x00033] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery (MySql.Data.MySqlClient.MySqlConnection connection, System.String commandText, MySql.Data.MySqlClient.MySqlParameter[] commandParameters) [0x00041] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at MySql.Data.MySqlClient.MySqlHelper.ExecuteNonQuery (System.String connectionString, System.String commandText, MySql.Data.MySqlClient.MySqlParameter[] parms) [0x0000d] in <0a135c8e4d604d948724bf6960583b7f>:0
	  at WhiteCore.DataManager.MySQL.MySQLDataLoader.ExecuteNonQuery (System.String connStr, System.String sql, System.Collections.Generic.Dictionary`2[TKey,TValue] parameters, System.Boolean spamConsole) [0x00052] in <8e239177980944678a0f544a3b549674>:0
	Jul 05 08:39:28 - [LLLoginService]: User did not have a home, set to 04363519-1c12-438d-8b80-46a21a87f241
	Jul 05 08:39:29 - [LLogin service]: All clear. Sending response to client for login to region ebim1 at <128, 128, 25>.
	WhiteCore.Server #

**Comment by emperorstarfinder** [comment] 2017-07-06 05:41
@greythane I have actually seen this error myself in testing:

Estate owner name (/User Name) []: felipe urrego
Do you want to 'park' the region with the system owner/estate? (yes/no) [yes]: enter

Jul 04 03:56:17 - [EVENT MANAGER]: Delegate for StartupComplete failed - continuing.  System.NullReferenceException: Object reference not set to an instance of an object
  at WhiteCore.Modules.Sun.SunModule.EventManager_OnStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] data) [0x00028] in <d01b8503b0fa49b6b0ff3792b62404e5>:0
  at WhiteCore.Framework.SceneInfo.EventManager.TriggerStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] StartupData) [0x00029] in <aba23f3718e649889efa69591d853d01>:0    at WhiteCore.Modules.Sun.SunModule.EventManager_OnStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] data) [0x00028] in <d01b8503b0fa49b6b0ff3792b62404e5>:0
  at WhiteCore.Framework.SceneInfo.EventManager.TriggerStartupComplete (WhiteCore.Framework.SceneInfo.IScene scene, System.Collections.Generic.List`1[T] StartupData) [0x00029] in <aba23f3718e649889efa69591d853d01>:0
Jul 04 03:56:17 - [WebUtils] Request failed - (URI:SyncMessageServerURI, METHOD:POST) : The request URI must either be an absolute URI or BaseAddress must be set
Jul 04 03:56:17 - [SceneManager]: Startup Complete. This took 0m 45.813s

Even with a fresh copy this one appears to happen when its the first initial region created.  However restarting the grid appears to fix it.  What causes it I have no idea myself but that one at least I can confirm does actually happen.

**Comment by greythane** [comment] 2017-07-21 06:34
Duplicated with #287 which has an attached video that may reveal what is happening
Closing to avoid confusion with multiple similar questions

**Closed by greythane** 2017-07-21 06:34 UTC
Labels: bug
