### ISSUE TITLE
error after run from run configurator

### ISSUE THREAD

**Issue by BogusCurry** [WhiteCoreSim/WhiteCore-Dev#189] opened 2016-03-18 07:40 UTC
### Steps to reproduce

1. make comand  run configurator in server console
After all the question, comes this error messages 
http://paste.md-5.net/weyufosuji.xml

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Server configuration

**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2
**Database:**
mysql
**WhiteCore version:**
0.9.4. dev gitversion from today
### Logs
http://paste.md-5.net/weyufosuji.xml

Please make sure that WhiteCore has made an log-file and include a link to it here

**Comment by greythane** [comment] 2016-03-18 07:52
Interesting as it does appear the required file is present and is the correct case.
I will check this and see what is happening as it appears the example template is not being found.

**Comment by greythane** [comment] 2016-03-18 08:38
I have just checked  the 'run configurator' command on an XUbuntu vm without any problem.

Your error was when running the configurator command once the server was started or was this configuration process entered immediately on startup?
If configuration was requested on startup this does indicate that the 'Config' directory was not found as this does contain a valid initial configuration.  Using the 'grid_console.sh' startup script should run correctly with no configuration changes. Once running, the final 'running configuration' can be set using the 'run configurator' command.

I will also provide a '--config' option switch to set the server configuration from startup rather than having to load up assets into an SQLite database that may ultimately be discarded.

**Comment by BogusCurry** [comment] 2016-03-18 11:28
yes the file is present in the config folder ;D

**Comment by emperorstarfinder** [comment] 2016-03-18 14:00
I tested this as well using KUbuntu with no problems.  The straight Ubuntu maybe the culprit here.  I recommend trying the WhiteCore.Server.sh from the bin directory.  Why that would be I have no idea as XUbuntu and KUbuntu are essentially custom versions of the Ubuntu operating system.

I also had this same error reported to me with the VU grid_console and the solution appears to have been to use the actual sh file for the corresponding server they were running.  

Hope that helps a little anyway.

**Comment by BogusCurry** [comment] 2016-03-18 17:42
Normal when the script is chmod 777, then I can start without sudo .. so I thinking ;D

**Comment by emperorstarfinder** [comment] 2016-03-18 17:48
So I take it that helped?

**Comment by BogusCurry** [comment] 2016-03-18 17:59
I not know, will test it later ;D

**Comment by emperorstarfinder** [comment] 2016-03-18 18:05
Oh okay.  Essentially chmod 777 is like saying it should be able to run as sudo but it may very well just be caused by a permissions thing in the main distro of Ubuntu.  So in theory you would be correct it should work.

**Comment by BogusCurry** [comment] 2016-03-18 18:25
sudo must make, when the server run under a another user account or permissions.

**Comment by greythane** [comment] 2016-03-18 21:21
You should not need to make as 'sudo' or chmod files.
Also running the scripts as 'sudo' will only hide any other problems.

Clone the repo whilst logged in as the user you will be running under.
Eg.  adduser mysim .... Etc. On Linux you can execute the 'autobuild.sh' script to configure and build for your system. (Corrections to this in the current repo)
After this, copy the entire WhiteCoreSim directory and paste it outside your build environment. Eg. 'mysim's  home directory. This will be the running version of your grid/sim and where you will make Config changes and run from.

The easiest way to run a grid setup is to use the 'run_gridmode.sh' script.  This will run both the grid server and region server in individual screen sessions so you will not block the current terminal session.
I also have scripts and instructions for upstart configs to auto start at boot if required.

To run as a different user, copy/paste the entire WhiteCoreSim directory in the new user's home directory.
  cd /home/newuser.  
  sudo chown newuser:newuser -R ./WhiteCoreSim
You are now ready to configure and run as the new user.

**Comment by greythane** [comment] 2016-03-22 01:59
The 'run configurator' command has been verified to work correctly is file permissions are correct.
This does appear to be a case of permission errors.

**Comment by BogusCurry** [comment] 2016-03-22 08:24
ok, then will I test it with the user account :D

**Comment by BogusCurry** [comment] 2016-03-31 12:11
Hi there ;D
Ok, I have make a little another way, I create user whitesim, the put in the file sudoers. Ok, then have clone the source to the new user and migration the database to the grid. Then I have run the configurator. No errors ;D
I can see in my webgui that the old regions are offline. The new region, create with the configurator is no there, but I see the message the comes online bye start. 

I am now a little confius ;D

Have a nice Day ;D

**Comment by emperorstarfinder** [comment] 2016-03-31 14:02
In the Data/Region folder has the region file been created?

Also it is not generally necessary to create a sudo user on Ubuntu to run a sudo command this could be the issue as well but first look to see that the region file was actually created.

**Comment by BogusCurry** [comment] 2016-03-31 21:30
the region file was created

**Comment by greythane** [comment] 2016-03-31 23:22
A couple of things...

You do not need to run WhiteCore using sudo UNLESS you are using port 80 for the WebUI.
With the standard configuration options, running as a 'normal' user is OK.  You should not need to 'sudo...' anything when compiling etc. 

Running the configurator only creates the configuration files. It does not create or copy any existing region data.

For your setup you need to do....
Create your user 'whitesim'  ... done
Copy/clone the repo as that user... done
Build whiteCore ... done

To finish the migration to a new user....
Copy the entire 'WhiteCoreSim' directory from the repo where you built WhiteCore, to your user's home directory.  Use your file manager or from the terminal...
 $  cd ~/WhiteCore-Dev
  $ cp ./WhiteCoreSim  ~/

You should now have the entire directory 'whiteCoreSim' in your users home directory 
 - This will be where your sim will run from.  
 - You should not run it from the cloned repo as any updates will overwrite your configuration setup

To use any existing data...
Rename (for safety) the existing 'Data' directory in your new installation i.e. WhiteCoreSim/Data
Copy (or move) the entire 'Data' directory from your previous installation to your new installation.  This directory contains all the configurations and region data.
You will need to change ownership on the old files to allow access by the new user.
i.e. $  chown whitesim:whitesim -R ./Data     (in your new user's WhiteCoreSim directory)

If you have migrated your data or not changed the MySql database/user/password then you should be ready to go.  If you have changed or need to change anything run WhiteCore with the '-config' switch to configure everything before trying to load region data etc.

For your grid setup...
$  mono WhiteCore.Server.exe -config   -- configure as required
   --  This will configure the grid server. Do this before running the region server
Startup the grid server either manually or via a script.  $ mono whiteCore.Server.exe  or ./grid_console.sh
Your grid services should start up and run without any errors.

For your region setup...   (with the grid server up and running)
$ mono WhiteCore.exe -config   -- configure as required

At the end of the configuration process you should have your new setup running using the old data.
 
An easier process is... 
(You will need to do this using 'sudo' as you will be copying between users and hence will need to ignore permissions.)

Copy the entire WhiteCoreSim from your OLD setup to the new user's home directory
Change to the NEW user's home folder.
Correct the ownership of the copied WhiteCoreSim directory.
 $ sudo chown:newuser:newuser -R ./WhiteCoreSim

Once this is done you should have the old setup running as your new user.  You can now update as the new user if required.

**Comment by greythane** [comment] 2016-07-05 22:38
Closing as this been resolved

**Closed by greythane** 2016-07-05 22:38 UTC
Labels: feature
